[package]
name = "multimorbidity_hypergraphs_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"
itertools = "0.11.0"
rayon = "1.7.0"
